### PR TITLE
fix(import): allow resource without side

### LINKED ISSUE #93: [BUG] import module doesn't work
### Summary

Importing module throws an error

### Reproduction

Screenshot_2

Screenshot_3

### Expected behavior

no errors and the module can be used

### Actual behavior

the opposite

### Additional context

_No response_

### Last Updated

2 days ago

### Custom Resources

no

### Resource Rename

no

### PR DESCRIPTION
**Pull request by BerkieBb**
## Description

Fixes #93 

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

### CODE REVIEW

File: import.lua [hunk 1]
```diff
@@ -43,7 +43,7 @@ local function checkModule(module, resourceName)
         side = not isSide and 'shared' or side
 
         doLoad = checkSide(side)
-        file = isResource and isSide and split[3] or not isResource and isSide and split[2] or split[1]
+        file = isResource and isSide and split[3] or (not isResource and isSide or isResource and not isSide) and split[2] or split[1]
```
Comment (Manason) [inline import.lua:46]: Consider breaking up using if statements, or extracting pieces to a named function to improve readability.

**Review by Manason — APPROVED** [review]
